// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tables.sql

package db

import (
	"context"
)

const countTables = `-- name: CountTables :one
SELECT COUNT(*) FROM tables
`

func (q *Queries) CountTables(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTables)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (id, table_number, capacity, status)
VALUES (?, ?, ?, 'available')
RETURNING id, table_number, capacity, status, created_at, updated_at
`

type CreateTableParams struct {
	ID          string `json:"id"`
	TableNumber string `json:"table_number"`
	Capacity    int64  `json:"capacity"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.ID, arg.TableNumber, arg.Capacity)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTable = `-- name: DeleteTable :exec
DELETE FROM tables
WHERE id = ?
`

func (q *Queries) DeleteTable(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTable, id)
	return err
}

const getAllTables = `-- name: GetAllTables :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
ORDER BY table_number
`

func (q *Queries) GetAllTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getAllTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableTables = `-- name: GetAvailableTables :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
WHERE status = 'available'
ORDER BY table_number
`

func (q *Queries) GetAvailableTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOccupiedTables = `-- name: GetOccupiedTables :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
WHERE status = 'occupied'
ORDER BY table_number
`

func (q *Queries) GetOccupiedTables(ctx context.Context) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getOccupiedTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTableByID(ctx context.Context, id string) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByID, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTableByNumber = `-- name: GetTableByNumber :one
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
WHERE table_number = ? LIMIT 1
`

func (q *Queries) GetTableByNumber(ctx context.Context, tableNumber string) (Table, error) {
	row := q.db.QueryRowContext(ctx, getTableByNumber, tableNumber)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.Capacity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTablesByStatus = `-- name: GetTablesByStatus :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
WHERE status = ?
ORDER BY table_number
`

func (q *Queries) GetTablesByStatus(ctx context.Context, status string) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, getTablesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesPaginated = `-- name: ListTablesPaginated :many
SELECT id, table_number, capacity, status, created_at, updated_at FROM tables
ORDER BY id
LIMIT ? OFFSET ?
`

type ListTablesPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTablesPaginated(ctx context.Context, arg ListTablesPaginatedParams) ([]Table, error) {
	rows, err := q.db.QueryContext(ctx, listTablesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.TableNumber,
			&i.Capacity,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTable = `-- name: UpdateTable :exec
UPDATE tables
SET table_number = ?, capacity = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateTableParams struct {
	TableNumber string `json:"table_number"`
	Capacity    int64  `json:"capacity"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateTable(ctx context.Context, arg UpdateTableParams) error {
	_, err := q.db.ExecContext(ctx, updateTable, arg.TableNumber, arg.Capacity, arg.ID)
	return err
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE tables
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE table_number = ?
`

type UpdateTableStatusParams struct {
	Status      string `json:"status"`
	TableNumber string `json:"table_number"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTableStatus, arg.Status, arg.TableNumber)
	return err
}
