// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_orders.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getActiveOrderByTable = `-- name: GetActiveOrderByTable :one
SELECT id, table_number, customer_name, customer_phone, customer_id, pax, basket_size, total_amount, paid_amount, order_status, created_by, payment_status, merged_from, is_merged, created_at, updated_at FROM orders
WHERE table_number = ?
AND payment_status != 'paid'
AND is_merged = 0
AND voided_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOrderByTableRow struct {
	ID            string         `json:"id"`
	TableNumber   string         `json:"table_number"`
	CustomerName  sql.NullString `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
	CustomerID    sql.NullString `json:"customer_id"`
	Pax           int64          `json:"pax"`
	BasketSize    int64          `json:"basket_size"`
	TotalAmount   float64        `json:"total_amount"`
	PaidAmount    float64        `json:"paid_amount"`
	OrderStatus   string         `json:"order_status"`
	CreatedBy     sql.NullString `json:"created_by"`
	PaymentStatus string         `json:"payment_status"`
	MergedFrom    sql.NullString `json:"merged_from"`
	IsMerged      int64          `json:"is_merged"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

// Get the latest active order for a table (not yet paid)
func (q *Queries) GetActiveOrderByTable(ctx context.Context, tableNumber string) (GetActiveOrderByTableRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrderByTable, tableNumber)
	var i GetActiveOrderByTableRow
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerID,
		&i.Pax,
		&i.BasketSize,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.OrderStatus,
		&i.CreatedBy,
		&i.PaymentStatus,
		&i.MergedFrom,
		&i.IsMerged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
