// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, description, printer_id, created_at, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, printer_id, created_at, updated_at
`

type CreateCategoryParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PrinterID   sql.NullString `json:"printer_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PrinterID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrinterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT 
    c.id, c.name, c.description, c.printer_id, c.created_at, c.updated_at,
    p.name as printer_name,
    p.printer_type as printer_type
FROM categories c
LEFT JOIN printers p ON c.printer_id = p.id
WHERE c.id = ? LIMIT 1
`

type GetCategoryRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PrinterID   sql.NullString `json:"printer_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	PrinterName sql.NullString `json:"printer_name"`
	PrinterType sql.NullString `json:"printer_type"`
}

func (q *Queries) GetCategory(ctx context.Context, id string) (GetCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i GetCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PrinterID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrinterName,
		&i.PrinterType,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT 
    c.id, c.name, c.description, c.printer_id, c.created_at, c.updated_at,
    p.name as printer_name,
    p.printer_type as printer_type,
    COUNT(DISTINCT pr.id) as product_count
FROM categories c
LEFT JOIN printers p ON c.printer_id = p.id
LEFT JOIN products pr ON c.id = pr.category_id
GROUP BY c.id, c.name, c.description, c.printer_id, c.created_at, c.updated_at, p.name, p.printer_type
ORDER BY c.id
`

type ListCategoriesRow struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	PrinterID    sql.NullString `json:"printer_id"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	PrinterName  sql.NullString `json:"printer_name"`
	PrinterType  sql.NullString `json:"printer_type"`
	ProductCount int64          `json:"product_count"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrinterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrinterName,
			&i.PrinterType,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesPaginated = `-- name: ListCategoriesPaginated :many
SELECT 
    c.id, c.name, c.description, c.printer_id, c.created_at, c.updated_at,
    p.name as printer_name,
    p.printer_type as printer_type
FROM categories c
LEFT JOIN printers p ON c.printer_id = p.id
ORDER BY c.id
LIMIT ? OFFSET ?
`

type ListCategoriesPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListCategoriesPaginatedRow struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PrinterID   sql.NullString `json:"printer_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	PrinterName sql.NullString `json:"printer_name"`
	PrinterType sql.NullString `json:"printer_type"`
}

func (q *Queries) ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]ListCategoriesPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesPaginatedRow{}
	for rows.Next() {
		var i ListCategoriesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PrinterID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrinterName,
			&i.PrinterType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET name = ?, description = ?, printer_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCategoryParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PrinterID   sql.NullString `json:"printer_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.PrinterID,
		arg.ID,
	)
	return err
}
