// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (id, name, phone)
VALUES (?, ?, ?)
RETURNING id, name, phone, created_at, updated_at
`

type CreateCustomerParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer, arg.ID, arg.Name, arg.Phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, phone, created_at, updated_at FROM customers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, created_at, updated_at FROM customers
WHERE phone = ? LIMIT 1
`

func (q *Queries) GetCustomerByPhone(ctx context.Context, phone string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByPhone, phone)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopCustomers = `-- name: GetTopCustomers :many
SELECT
    c.id,
    c.name,
    c.phone,
    COUNT(o.id) AS total_orders,
    SUM(o.total_amount) AS total_spent
FROM customers c
JOIN orders o ON o.customer_id = c.id
WHERE o.payment_status = 'paid'
AND o.created_at BETWEEN ?1 AND ?2
GROUP BY c.id
ORDER BY total_spent DESC
LIMIT ?3
`

type GetTopCustomersRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Phone       string          `json:"phone"`
	TotalOrders int64           `json:"total_orders"`
	TotalSpent  sql.NullFloat64 `json:"total_spent"`
}

func (q *Queries) GetTopCustomers(ctx context.Context, limit int64) ([]GetTopCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopCustomers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopCustomersRow{}
	for rows.Next() {
		var i GetTopCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.TotalOrders,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
