// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	PrinterID   sql.NullString `json:"printer_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Customer struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID            string         `json:"id"`
	TableNumber   string         `json:"table_number"`
	CustomerName  sql.NullString `json:"customer_name"`
	CustomerPhone sql.NullString `json:"customer_phone"`
	CustomerID    sql.NullString `json:"customer_id"`
	Pax           int64          `json:"pax"`
	BasketSize    int64          `json:"basket_size"`
	TotalAmount   float64        `json:"total_amount"`
	PaidAmount    float64        `json:"paid_amount"`
	OrderStatus   string         `json:"order_status"`
	CreatedBy     sql.NullString `json:"created_by"`
	PaymentStatus string         `json:"payment_status"`
	MergedFrom    sql.NullString `json:"merged_from"`
	IsMerged      int64          `json:"is_merged"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type OrderItem struct {
	ID          string    `json:"id"`
	OrderID     string    `json:"order_id"`
	ProductName string    `json:"product_name"`
	Qty         int64     `json:"qty"`
	Price       float64   `json:"price"`
	Destination string    `json:"destination"`
	ItemStatus  string    `json:"item_status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Payment struct {
	ID            string         `json:"id"`
	OrderID       string         `json:"order_id"`
	Amount        float64        `json:"amount"`
	PaymentMethod string         `json:"payment_method"`
	PaymentNote   sql.NullString `json:"payment_note"`
	CreatedBy     string         `json:"created_by"`
	CreatedAt     time.Time      `json:"created_at"`
}

type PrintQueue struct {
	ID           string         `json:"id"`
	PrinterID    string         `json:"printer_id"`
	Data         string         `json:"data"`
	Status       string         `json:"status"`
	RetryCount   int64          `json:"retry_count"`
	ErrorMessage sql.NullString `json:"error_message"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	LockedAt     sql.NullTime   `json:"locked_at"`
	LockedBy     sql.NullString `json:"locked_by"`
}

type Printer struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	IpAddress         string         `json:"ip_address"`
	Port              int64          `json:"port"`
	PrinterType       string         `json:"printer_type"`
	PaperSize         string         `json:"paper_size"`
	ConnectionTimeout sql.NullInt64  `json:"connection_timeout"`
	WriteTimeout      sql.NullInt64  `json:"write_timeout"`
	RetryAttempts     sql.NullInt64  `json:"retry_attempts"`
	PrintDensity      sql.NullInt64  `json:"print_density"`
	PrintSpeed        sql.NullString `json:"print_speed"`
	CutMode           sql.NullString `json:"cut_mode"`
	EnableBeep        sql.NullInt64  `json:"enable_beep"`
	AutoCut           sql.NullInt64  `json:"auto_cut"`
	Charset           sql.NullString `json:"charset"`
	IsActive          int64          `json:"is_active"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type Product struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Code        sql.NullString `json:"code"`
	Description sql.NullString `json:"description"`
	Price       float64        `json:"price"`
	Stock       int64          `json:"stock"`
	CategoryID  sql.NullString `json:"category_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Table struct {
	ID          string    `json:"id"`
	TableNumber string    `json:"table_number"`
	Capacity    int64     `json:"capacity"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Transaction struct {
	ID              string         `json:"id"`
	OrderID         string         `json:"order_id"`
	TotalAmount     float64        `json:"total_amount"`
	PaymentMethod   string         `json:"payment_method"`
	Status          string         `json:"status"`
	TransactionDate time.Time      `json:"transaction_date"`
	CreatedBy       sql.NullString `json:"created_by"`
	CancelledAt     sql.NullTime   `json:"cancelled_at"`
	CancelledBy     sql.NullString `json:"cancelled_by"`
	CancelReason    sql.NullString `json:"cancel_reason"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type TransactionItem struct {
	ID            string  `json:"id"`
	TransactionID string  `json:"transaction_id"`
	ProductID     string  `json:"product_id"`
	Quantity      int64   `json:"quantity"`
	Price         float64 `json:"price"`
}

type User struct {
	ID           string    `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	FullName     string    `json:"full_name"`
	Role         string    `json:"role"`
	IsActive     int64     `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
