// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: printers.sql

package db

import (
	"context"
	"database/sql"
)

const countPrinters = `-- name: CountPrinters :one
SELECT COUNT(*) FROM printers
`

func (q *Queries) CountPrinters(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrinters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrinter = `-- name: CreatePrinter :one
INSERT INTO printers (
    id, name, ip_address, port, printer_type, paper_size, is_active,
    connection_timeout, write_timeout, retry_attempts,
    print_density, print_speed, cut_mode,
    enable_beep, auto_cut, charset,
    created_at, updated_at
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, ip_address, port, printer_type, paper_size, connection_timeout, write_timeout, retry_attempts, print_density, print_speed, cut_mode, enable_beep, auto_cut, charset, is_active, created_at, updated_at
`

type CreatePrinterParams struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	IpAddress         string         `json:"ip_address"`
	Port              int64          `json:"port"`
	PrinterType       string         `json:"printer_type"`
	PaperSize         string         `json:"paper_size"`
	IsActive          int64          `json:"is_active"`
	ConnectionTimeout sql.NullInt64  `json:"connection_timeout"`
	WriteTimeout      sql.NullInt64  `json:"write_timeout"`
	RetryAttempts     sql.NullInt64  `json:"retry_attempts"`
	PrintDensity      sql.NullInt64  `json:"print_density"`
	PrintSpeed        sql.NullString `json:"print_speed"`
	CutMode           sql.NullString `json:"cut_mode"`
	EnableBeep        sql.NullInt64  `json:"enable_beep"`
	AutoCut           sql.NullInt64  `json:"auto_cut"`
	Charset           sql.NullString `json:"charset"`
}

func (q *Queries) CreatePrinter(ctx context.Context, arg CreatePrinterParams) (Printer, error) {
	row := q.db.QueryRowContext(ctx, createPrinter,
		arg.ID,
		arg.Name,
		arg.IpAddress,
		arg.Port,
		arg.PrinterType,
		arg.PaperSize,
		arg.IsActive,
		arg.ConnectionTimeout,
		arg.WriteTimeout,
		arg.RetryAttempts,
		arg.PrintDensity,
		arg.PrintSpeed,
		arg.CutMode,
		arg.EnableBeep,
		arg.AutoCut,
		arg.Charset,
	)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.Port,
		&i.PrinterType,
		&i.PaperSize,
		&i.ConnectionTimeout,
		&i.WriteTimeout,
		&i.RetryAttempts,
		&i.PrintDensity,
		&i.PrintSpeed,
		&i.CutMode,
		&i.EnableBeep,
		&i.AutoCut,
		&i.Charset,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePrinter = `-- name: DeletePrinter :exec
DELETE FROM printers
WHERE id = ?
`

func (q *Queries) DeletePrinter(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePrinter, id)
	return err
}

const getPrinter = `-- name: GetPrinter :one
SELECT id, name, ip_address, port, printer_type, paper_size, connection_timeout, write_timeout, retry_attempts, print_density, print_speed, cut_mode, enable_beep, auto_cut, charset, is_active, created_at, updated_at FROM printers
WHERE id = ?
`

func (q *Queries) GetPrinter(ctx context.Context, id string) (Printer, error) {
	row := q.db.QueryRowContext(ctx, getPrinter, id)
	var i Printer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.Port,
		&i.PrinterType,
		&i.PaperSize,
		&i.ConnectionTimeout,
		&i.WriteTimeout,
		&i.RetryAttempts,
		&i.PrintDensity,
		&i.PrintSpeed,
		&i.CutMode,
		&i.EnableBeep,
		&i.AutoCut,
		&i.Charset,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePrinters = `-- name: ListActivePrinters :many
SELECT id, name, ip_address, port, printer_type, paper_size, connection_timeout, write_timeout, retry_attempts, print_density, print_speed, cut_mode, enable_beep, auto_cut, charset, is_active, created_at, updated_at FROM printers
WHERE is_active = 1
ORDER BY printer_type, name
`

func (q *Queries) ListActivePrinters(ctx context.Context) ([]Printer, error) {
	rows, err := q.db.QueryContext(ctx, listActivePrinters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Printer{}
	for rows.Next() {
		var i Printer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.Port,
			&i.PrinterType,
			&i.PaperSize,
			&i.ConnectionTimeout,
			&i.WriteTimeout,
			&i.RetryAttempts,
			&i.PrintDensity,
			&i.PrintSpeed,
			&i.CutMode,
			&i.EnableBeep,
			&i.AutoCut,
			&i.Charset,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrinters = `-- name: ListPrinters :many
SELECT id, name, ip_address, port, printer_type, paper_size, connection_timeout, write_timeout, retry_attempts, print_density, print_speed, cut_mode, enable_beep, auto_cut, charset, is_active, created_at, updated_at FROM printers
ORDER BY printer_type, name
`

func (q *Queries) ListPrinters(ctx context.Context) ([]Printer, error) {
	rows, err := q.db.QueryContext(ctx, listPrinters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Printer{}
	for rows.Next() {
		var i Printer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.Port,
			&i.PrinterType,
			&i.PaperSize,
			&i.ConnectionTimeout,
			&i.WriteTimeout,
			&i.RetryAttempts,
			&i.PrintDensity,
			&i.PrintSpeed,
			&i.CutMode,
			&i.EnableBeep,
			&i.AutoCut,
			&i.Charset,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrintersByType = `-- name: ListPrintersByType :many
SELECT id, name, ip_address, port, printer_type, paper_size, connection_timeout, write_timeout, retry_attempts, print_density, print_speed, cut_mode, enable_beep, auto_cut, charset, is_active, created_at, updated_at FROM printers
WHERE printer_type = ? AND is_active = 1
ORDER BY name
`

func (q *Queries) ListPrintersByType(ctx context.Context, printerType string) ([]Printer, error) {
	rows, err := q.db.QueryContext(ctx, listPrintersByType, printerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Printer{}
	for rows.Next() {
		var i Printer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IpAddress,
			&i.Port,
			&i.PrinterType,
			&i.PaperSize,
			&i.ConnectionTimeout,
			&i.WriteTimeout,
			&i.RetryAttempts,
			&i.PrintDensity,
			&i.PrintSpeed,
			&i.CutMode,
			&i.EnableBeep,
			&i.AutoCut,
			&i.Charset,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const togglePrinterActive = `-- name: TogglePrinterActive :exec
UPDATE printers
SET is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type TogglePrinterActiveParams struct {
	IsActive int64  `json:"is_active"`
	ID       string `json:"id"`
}

func (q *Queries) TogglePrinterActive(ctx context.Context, arg TogglePrinterActiveParams) error {
	_, err := q.db.ExecContext(ctx, togglePrinterActive, arg.IsActive, arg.ID)
	return err
}

const updatePrinter = `-- name: UpdatePrinter :exec
UPDATE printers
SET name = ?, ip_address = ?, port = ?, printer_type = ?, paper_size = ?, is_active = ?,
    connection_timeout = ?, write_timeout = ?, retry_attempts = ?,
    print_density = ?, print_speed = ?, cut_mode = ?,
    enable_beep = ?, auto_cut = ?, charset = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePrinterParams struct {
	Name              string         `json:"name"`
	IpAddress         string         `json:"ip_address"`
	Port              int64          `json:"port"`
	PrinterType       string         `json:"printer_type"`
	PaperSize         string         `json:"paper_size"`
	IsActive          int64          `json:"is_active"`
	ConnectionTimeout sql.NullInt64  `json:"connection_timeout"`
	WriteTimeout      sql.NullInt64  `json:"write_timeout"`
	RetryAttempts     sql.NullInt64  `json:"retry_attempts"`
	PrintDensity      sql.NullInt64  `json:"print_density"`
	PrintSpeed        sql.NullString `json:"print_speed"`
	CutMode           sql.NullString `json:"cut_mode"`
	EnableBeep        sql.NullInt64  `json:"enable_beep"`
	AutoCut           sql.NullInt64  `json:"auto_cut"`
	Charset           sql.NullString `json:"charset"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdatePrinter(ctx context.Context, arg UpdatePrinterParams) error {
	_, err := q.db.ExecContext(ctx, updatePrinter,
		arg.Name,
		arg.IpAddress,
		arg.Port,
		arg.PrinterType,
		arg.PaperSize,
		arg.IsActive,
		arg.ConnectionTimeout,
		arg.WriteTimeout,
		arg.RetryAttempts,
		arg.PrintDensity,
		arg.PrintSpeed,
		arg.CutMode,
		arg.EnableBeep,
		arg.AutoCut,
		arg.Charset,
		arg.ID,
	)
	return err
}
