// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"
	"database/sql"
)

const checkCodeExists = `-- name: CheckCodeExists :one
SELECT COUNT(*) FROM products
WHERE code = ? AND id != ?
`

type CheckCodeExistsParams struct {
	Code sql.NullString `json:"code"`
	ID   string         `json:"id"`
}

func (q *Queries) CheckCodeExists(ctx context.Context, arg CheckCodeExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCodeExists, arg.Code, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*) FROM products
WHERE (COALESCE(?, '') = '' OR name LIKE '%' || ? || '%' OR code LIKE '%' || ? || '%')
  AND (COALESCE(?, '') = '' OR category_id = ?)
`

type CountSearchProductsParams struct {
	Column1    interface{}    `json:"column_1"`
	Column2    sql.NullString `json:"column_2"`
	Column3    sql.NullString `json:"column_3"`
	Column4    interface{}    `json:"column_4"`
	CategoryID sql.NullString `json:"category_id"`
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.CategoryID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, name, code, description, price, stock, category_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, code, description, price, stock, category_id, created_at, updated_at
`

type CreateProductParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Code        sql.NullString `json:"code"`
	Description sql.NullString `json:"description"`
	Price       float64        `json:"price"`
	Stock       int64          `json:"stock"`
	CategoryID  sql.NullString `json:"category_id"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = ?
`

func (q *Queries) DeleteProduct(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByCode = `-- name: GetProductByCode :one
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
WHERE code = ? LIMIT 1
`

func (q *Queries) GetProductByCode(ctx context.Context, code sql.NullString) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByCode, code)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
ORDER BY id
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
WHERE category_id = ?
ORDER BY id
`

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID sql.NullString) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsPaginated = `-- name: ListProductsPaginated :many
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
ORDER BY id
LIMIT ? OFFSET ?
`

type ListProductsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductsPaginated = `-- name: SearchProductsPaginated :many
SELECT id, name, code, description, price, stock, category_id, created_at, updated_at FROM products
WHERE (COALESCE(?, '') = '' OR name LIKE '%' || ? || '%' OR code LIKE '%' || ? || '%')
  AND (COALESCE(?, '') = '' OR category_id = ?)
ORDER BY id
LIMIT ? OFFSET ?
`

type SearchProductsPaginatedParams struct {
	Column1    interface{}    `json:"column_1"`
	Column2    sql.NullString `json:"column_2"`
	Column3    sql.NullString `json:"column_3"`
	Column4    interface{}    `json:"column_4"`
	CategoryID sql.NullString `json:"category_id"`
	Limit      int64          `json:"limit"`
	Offset     int64          `json:"offset"`
}

func (q *Queries) SearchProductsPaginated(ctx context.Context, arg SearchProductsPaginatedParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProductsPaginated,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.CategoryID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = ?, code = ?, description = ?, price = ?, stock = ?, category_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateProductParams struct {
	Name        string         `json:"name"`
	Code        sql.NullString `json:"code"`
	Description sql.NullString `json:"description"`
	Price       float64        `json:"price"`
	Stock       int64          `json:"stock"`
	CategoryID  sql.NullString `json:"category_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.CategoryID,
		arg.ID,
	)
	return err
}
