// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ActivateUser(ctx context.Context, id string) error
	CheckCodeExists(ctx context.Context, arg CheckCodeExistsParams) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountPrinters(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error)
	CountTables(ctx context.Context) (int64, error)
	CountTransactions(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CancelTransaction(ctx context.Context, arg CancelTransactionParams) (Transaction, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (string, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintQueue, error)
	CreatePrinter(ctx context.Context, arg CreatePrinterParams) (Printer, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id string) error
	DeleteCategory(ctx context.Context, id string) error
	DeletePrinter(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteTable(ctx context.Context, id string) error
	// Get the latest active order for a table (not yet paid)
	GetActiveOrderByTable(ctx context.Context, tableNumber string) (Order, error)
	GetAllTables(ctx context.Context) ([]Table, error)
	GetAvailableTables(ctx context.Context) ([]Table, error)
	GetCategory(ctx context.Context, id string) (GetCategoryRow, error)
	GetCustomerByID(ctx context.Context, id string) (Customer, error)
	GetCustomerByPhone(ctx context.Context, phone string) (Customer, error)
	GetMergedOrders(ctx context.Context, mergedFrom sql.NullString) ([]Order, error)
	GetOccupiedTables(ctx context.Context) ([]Table, error)
	GetOrderAnalytics(ctx context.Context, arg GetOrderAnalyticsParams) (GetOrderAnalyticsRow, error)
	GetOrderItems(ctx context.Context, orderID string) ([]OrderItem, error)
	GetOrderTotalPaid(ctx context.Context, orderID string) (interface{}, error)
	GetOrderWithItems(ctx context.Context, id string) (Order, error)
	GetOrdersByTable(ctx context.Context, tableNumber string) ([]Order, error)
	GetPaymentsByOrder(ctx context.Context, orderID string) ([]Payment, error)
	GetPendingOrders(ctx context.Context) ([]Order, error)
	GetPendingPrintJobs(ctx context.Context) ([]PrintQueue, error)
	GetPrinter(ctx context.Context, id string) (Printer, error)
	GetProduct(ctx context.Context, id string) (Product, error)
	GetProductByCode(ctx context.Context, code sql.NullString) (Product, error)
	GetProductsSold(ctx context.Context, arg GetProductsSoldParams) (interface{}, error)
	GetRevenueByDay(ctx context.Context, arg GetRevenueByDayParams) ([]GetRevenueByDayRow, error)
	GetRevenueByHour(ctx context.Context, createdAt time.Time) ([]GetRevenueByHourRow, error)
	GetRevenueByPaymentStatus(ctx context.Context, arg GetRevenueByPaymentStatusParams) (GetRevenueByPaymentStatusRow, error)
	GetTableByID(ctx context.Context, id string) (Table, error)
	GetTableByNumber(ctx context.Context, tableNumber string) (Table, error)
	GetTablesByStatus(ctx context.Context, status string) ([]Table, error)
	GetTopCustomers(ctx context.Context, limit int64) ([]GetTopCustomersRow, error)
	GetTransaction(ctx context.Context, id string) (Transaction, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListActivePrinters(ctx context.Context) ([]Printer, error)
	ListCategories(ctx context.Context) ([]ListCategoriesRow, error)
	ListCategoriesPaginated(ctx context.Context, arg ListCategoriesPaginatedParams) ([]ListCategoriesPaginatedRow, error)
	ListOrdersByCustomer(ctx context.Context, customerID sql.NullString) ([]Order, error)
	ListPrinters(ctx context.Context) ([]Printer, error)
	ListPrintersByType(ctx context.Context, printerType string) ([]Printer, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ListProductsByCategory(ctx context.Context, categoryID sql.NullString) ([]Product, error)
	ListProductsPaginated(ctx context.Context, arg ListProductsPaginatedParams) ([]Product, error)
	ListTablesPaginated(ctx context.Context, arg ListTablesPaginatedParams) ([]Table, error)
	ListTransactionItems(ctx context.Context, transactionID string) ([]ListTransactionItemsRow, error)
	ListTransactions(ctx context.Context) ([]Transaction, error)
	ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error)
	ListTransactionsPaginated(ctx context.Context, arg ListTransactionsPaginatedParams) ([]Transaction, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error)
	MergeOrders(ctx context.Context, arg MergeOrdersParams) error
	SearchProductsPaginated(ctx context.Context, arg SearchProductsPaginatedParams) ([]Product, error)
	TogglePrinterActive(ctx context.Context, arg TogglePrinterActiveParams) error
	TransferOrderItems(ctx context.Context, arg TransferOrderItemsParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateOrderItemStatus(ctx context.Context, arg UpdateOrderItemStatusParams) error
	UpdateOrderPaidAmount(ctx context.Context, arg UpdateOrderPaidAmountParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) error
	UpdatePaymentStatus(ctx context.Context, id string) error
	UpdatePrintJobStatus(ctx context.Context, arg UpdatePrintJobStatusParams) error
	UpdatePrinter(ctx context.Context, arg UpdatePrinterParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateTable(ctx context.Context, arg UpdateTableParams) error
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error
	UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) error
}

var _ Querier = (*Queries)(nil)
