// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_orders.sql

package db

import (
	"context"
)

const getActiveOrderByTable = `-- name: GetActiveOrderByTable :one
SELECT id, table_number, customer_name, customer_phone, customer_id, pax, basket_size, total_amount, paid_amount, order_status, created_by, payment_status, merged_from, is_merged, created_at, updated_at FROM orders
WHERE table_number = ?
AND payment_status != 'paid'
AND is_merged = 0
AND voided_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

// Get the latest active order for a table (not yet paid)
func (q *Queries) GetActiveOrderByTable(ctx context.Context, tableNumber string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrderByTable, tableNumber)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableNumber,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerID,
		&i.Pax,
		&i.BasketSize,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.OrderStatus,
		&i.CreatedBy,
		&i.PaymentStatus,
		&i.MergedFrom,
		&i.IsMerged,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
