// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, order_id, total_amount, payment_method, status, transaction_date, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, order_id, total_amount, payment_method, status, transaction_date, created_by, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
`

type CreateTransactionParams struct {
	ID              string    `json:"id"`
	OrderID         string    `json:"order_id"`
	TotalAmount     float64   `json:"total_amount"`
	PaymentMethod   string    `json:"payment_method"`
	Status          string    `json:"status"`
	TransactionDate time.Time `json:"transaction_date"`
	CreatedBy       string    `json:"created_by"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.OrderID,
		arg.TotalAmount,
		arg.PaymentMethod,
		arg.Status,
		arg.TransactionDate,
		arg.CreatedBy,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.Status,
		&i.TransactionDate,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelTransaction = `-- name: CancelTransaction :one
UPDATE transactions
SET status = ?, cancelled_at = ?, cancelled_by = ?, cancel_reason = ?, updated_at = ?
WHERE id = ?
RETURNING id, order_id, total_amount, payment_method, status, transaction_date, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at
`

type CancelTransactionParams struct {
	Status       string         `json:"status"`
	CancelledAt  sql.NullTime   `json:"cancelled_at"`
	CancelledBy  sql.NullString `json:"cancelled_by"`
	CancelReason sql.NullString `json:"cancel_reason"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ID           string         `json:"id"`
}

func (q *Queries) CancelTransaction(ctx context.Context, arg CancelTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, cancelTransaction,
		arg.Status,
		arg.CancelledAt,
		arg.CancelledBy,
		arg.CancelReason,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.Status,
		&i.TransactionDate,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (id, transaction_id, product_id, quantity, price)
VALUES (?, ?, ?, ?, ?)
RETURNING id, transaction_id, product_id, quantity, price
`

type CreateTransactionItemParams struct {
	ID            string  `json:"id"`
	TransactionID string  `json:"transaction_id"`
	ProductID     string  `json:"product_id"`
	Quantity      int64   `json:"quantity"`
	Price         float64 `json:"price"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRowContext(ctx, createTransactionItem,
		arg.ID,
		arg.TransactionID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, order_id, total_amount, payment_method, status, transaction_date, created_by, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at FROM transactions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.TotalAmount,
		&i.PaymentMethod,
		&i.Status,
		&i.TransactionDate,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionItems = `-- name: ListTransactionItems :many
SELECT ti.id, ti.transaction_id, ti.product_id, ti.quantity, ti.price, p.name as product_name
FROM transaction_items ti
LEFT JOIN products p ON ti.product_id = p.id
WHERE ti.transaction_id = ?
`

type ListTransactionItemsRow struct {
	ID            string         `json:"id"`
	TransactionID string         `json:"transaction_id"`
	ProductID     string         `json:"product_id"`
	Quantity      int64          `json:"quantity"`
	Price         float64        `json:"price"`
	ProductName   sql.NullString `json:"product_name"`
}

func (q *Queries) ListTransactionItems(ctx context.Context, transactionID string) ([]ListTransactionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionItemsRow{}
	for rows.Next() {
		var i ListTransactionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, order_id, total_amount, payment_method, status, transaction_date, created_by, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at FROM transactions
ORDER BY transaction_date DESC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TotalAmount,
			&i.PaymentMethod,
			&i.Status,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, order_id, total_amount, payment_method, status, transaction_date, created_by, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at FROM transactions
WHERE transaction_date BETWEEN ? AND ?
ORDER BY transaction_date DESC
`

type ListTransactionsByDateRangeParams struct {
	FromTransactionDate time.Time `json:"from_transaction_date"`
	ToTransactionDate   time.Time `json:"to_transaction_date"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg ListTransactionsByDateRangeParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByDateRange, arg.FromTransactionDate, arg.ToTransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TotalAmount,
			&i.PaymentMethod,
			&i.Status,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsPaginated = `-- name: ListTransactionsPaginated :many
SELECT id, order_id, total_amount, payment_method, status, transaction_date, created_by, cancelled_at, cancelled_by, cancel_reason, created_at, updated_at FROM transactions
ORDER BY transaction_date DESC
LIMIT ? OFFSET ?
`

type ListTransactionsPaginatedParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListTransactionsPaginated(ctx context.Context, arg ListTransactionsPaginatedParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.TotalAmount,
			&i.PaymentMethod,
			&i.Status,
			&i.TransactionDate,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
